[project]
name = "1d-heat-equation"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pybind11>=3.0.0",
    "pyqt6>=6.9.1",
]
